### ISSUE TITLE
Prepare for renewed OmniKassa?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-omnikassa-2#11]
> Inmiddels is de OmniKassa, die later dit jaar een nieuwe naam krijgt, opnieuw gebouwd en biedt het dezelfde betaalmogelijkheden als [payment service providers](https://www.ecommercenews.nl/tag/psp/).

https://www.ecommercenews.nl/rabobank-lanceert-partner-programma-voor-vernieuwde-omnikassa/

**Comment by rvdsteege** [comment]
The gateway has been updated to Rabo Smart Pay, I think this issue can be closed @remcotolsma?

**Comment by remcotolsma** [comment]
In addition to the name change, I had expected some technical changes, but that does not seem to be the case yet. Maybe @LeoOosterloo can take look at the partner program part in https://www.ecommercenews.nl/rabobank-lanceert-partner-programma-voor-vernieuwde-omnikassa/?

- https://www.rabobank.nl/bedrijven/betalen/klanten-laten-betalen/partnernetwerk

**Comment by LeoOosterloo** [comment]
I'm looking in to the options to take part of the Rabobank Partner Network. Made a specific todo for that:
https://github.com/pronamic/pronamic-pay/issues/24

Closing this issue because of that.
