### ISSUE TITLE
Rabo Smart Pay, the new name of Rabo OmniKassa

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-omnikassa-2#13]
We received the following email from Rabobank:

> # Rabo Smart Pay en jouw (boekhoud)pakket
> 
> Beste relatie,
> 
> Per 1 november aanstaande wijzigt de omschrijving van de omzetbijschrijving van Rabo OmniKassa op jouw zakelijke rekening. Dat is het gevolg van de naamsverandering van Rabo Omnikassa naar Rabo Smart Pay. Je ontvangt deze herinnering omdat je hierdoor mogelijk een aanpassing doen voor het (laten) inlezen van jouw rekeninggegevens in een (boekhoud)pakket. Hieronder lees je daarover meer.
> 
> **Mogelijke aanpassing nodig in (boekhoud)pakket**
> Het dagtotaal van Rabo OmniKassa wordt geboekt op jouw zakelijke rekening die gekoppeld is aan Rabo OmniKassa. Per 1 november aanstaande verandert de omschrijving van deze omzetbijschrijving: het woord ‘OmniKassa’ wordt vervangen door ‘Smart Pay’. Dit kan gevolgen hebben voor het (laten) inlezen van de rekeninggegevens van je zakelijke rekening in een (boekhoud)pakket. Bijvoorbeeld als jouw boekingen worden geselecteerd o.b.v. zoekwoorden of op een bepaalde positie in het omschrijvingsveld. Wellicht moet je hiervoor een aanpassing (laten) doorvoeren. Neem daarvoor contact op met de leverancier van je boekhoudpakket.
> 
> **Geen wijziging in transactieoverzicht Rabo OmniKassa (Rabo Smart Pay) dashboard**
> Er zijn geen wijzigingen in de omschrijving van de afzonderlijke transacties in het transactieoverzicht uit het Rabo OmniKassa (Rabo Smart Pay) dashboard. Hiervoor hoef je dus geen aanpassingen te (laten) doorvoeren in je boekhoudpakket.
> 
> **Meer informatie**
> Meer informatie over de naamswijziging vind je op [www.rabobank.nl/naamswijzigingsmartpay](http://www.rabobank.nl/naamswijzigingsmartpay).
> 
> Met vriendelijke groet,
> Support Team Rabo OmniKassa

On http://www.rabobank.nl/naamswijzigingsmartpay is some more information:

> **Waarom verandert de naam van Rabo OmniKassa?**
> De naam Rabo OmniKassa hebben we 10 jaar geleden gekozen toen Rabobank de eerste online betaaloplossingen voor ondernemers introduceerde. Nu zijn online betaaloplossingen een integraal onderdeel van onze dienstverlening en is ‘omnichannel’ de standaard geworden. Daarnaast komen er steeds meer slimme betaalmogelijkheden bij. Tijd dus voor een beter passende naam: Rabo Smart Pay

🤔

**Comment by rvdsteege** [comment]
Pending review of https://github.com/pronamic/wp-pronamic-pay-omnikassa-2/pull/14.
